all:
  children:
    linux:
      opensuse:
        packages:
          check: "zypper refresh && zypper patch-check --with-optional"
          refresh: "zypper refresh"
          update: "zypper --non-interactive up --auto-agree-with-licenses --replacefiles"
          clean: "zypper clean"
          orphans: "zypper packages --orphaned"
          list: "zypper list-updates"
          reboot: "zypper needs-rebooting"
        port: 2222
        hosts:
          Suse-Roll-01:
            enabled: false
            vm_host: Mom
            address: [ 10.145.156.3 ]
          Suse-Roll-02:
            enabled: false
            vm_host: DualBoot-Suse
            address: [ 192.168.0.2 ]
          Suse-Beta-01:
            enabled: false
            vm_host: Lab-Suse-01
            address: [ 10.145.156.5 ]
          DualBoot-Suse:
          Dad:
            enabled: true
            address: [ 192.168.0.1 ]
          Mom:
            enabled: true
            address: [ 192.168.0.2, 10.145.156.2 ]
          GateServer:
            enabled: false
            address: [ 192.168.0.18 ]
          Suse-Beta-16:
            enabled: false
            vm_host: Lab-Suse-01
          Suse-Weed-01:
            enabled: false
            vm_host: DualBoot-Suse
          Lab-Suse-01:
            enabled: true
            address: [ 192.168.0.67, 10.145.156.10 ]
      redhat:
        packages:
          check: "dnf check-update"
          refresh: "dnf check-update"
          update: "dnf upgrade -y"
          clean: "dnf clean all"
          list: "dnf list updates"
          reboot: "needs-restarting -r"
        hosts:
          rh10-beta-01:
            enabled: false
            address: [ 192.168.0.102 ]
          rh95-dev-01:
            enabled: false
            vm_host: Dad
            address: [ 192.168.0.103 ]
          rh10-dev-01:
            enabled: false
            vm_host: Dad
            address: [ 192.168.0.104 ]
      ubuntu:
        packages:
          check: "apt update && apt list --upgradeable"
          refresh: "apt update"
          update: "apt upgrade -y"
          full-update: "apt full-upgrade -y"
          clean: "apt autoremove -y"
          list: "apt list --upgradeable"
          reboot: "test -f /var/run/reboot-required"
        hosts:
          ub25-desk-01:
            enabled: false
            virt_host: GateServer
            address: [ 192.168.0.23 ]
          ub25-srvr-01:
            enabled: false
            virt_host: GateServer
            address: [ 192.168.0.88 ]
