#!/bin/sh
set -e

echo "RunUpdates has been installed into /opt/RunUpdates."

echo "NOTE: RunUpdates requires write access to /opt/RunUpdates."
echo "If you intend to run it as a non-root user, run:"
echo "  sudo chown -R <user>:<group> /opt/RunUpdates"

exit 0
