Name:           RunUpdates
Version:        %{version}
Release:        1%{?dist}
Summary:        RunUpdates system updater and automation tool

License:        Proprietary
URL:            https://linktechengineering.net/runupdates
Vendor:         Linktech Engineering
Packager:       Linktech Engineering Support <support@linktechengineering.net>
BuildArch:      x86_64
Requires:       /bin/bash

%description
RunUpdates is a system update orchestration tool. This RPM installs the frozen RunUpdates binary and the required runtime directories under /opt/RunUpdates, including configuration, schemata, logs, and run directories. All environment files and configuration templates are pre-generated by the build system.

%prep
# Nothing to prep — frozen build is already provided

%build
# No build step — binary is prebuilt

%install
rm -rf %{buildroot}
INSTALLROOT=%{buildroot}/opt/RunUpdates

# Copy the entire prebuilt tree from the source tarball
cp -r %{_sourcedir}/RunUpdates/* $INSTALLROOT/

%files
/opt/RunUpdates

%post
echo "RunUpdates installed."
echo "Configuration directory: /opt/RunUpdates/etc"
echo "Logs: /opt/RunUpdates/var/log"

%preun
echo "Uninstalling RunUpdates..."

%postun
echo "RunUpdates removed."
